name: "Build Debug"

on:
  workflow_dispatch:  # 👈 Allows manual trigger
  pull_request:
    branches:
      - master  # 👈 Added master
      - dev
      - test
  push:
    branches:
      - master  # 👈 Added master
      - dev
      - test

jobs:
  build:
    name: Build Debug
    runs-on: macos-latest

    steps:
      # 1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      # 3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      # 4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 5 Build Debug APK
      - name: Build Debug APK
        run: flutter build apk 

      # 8 Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Debug-Builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/bundle/debug/app-debug.aab
